# Generated by Django 3.2.5 on 2021-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='img',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
