# Generated by Django 3.2.5 on 2021-10-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_content',
            old_name='schedule_id',
            new_name='schedules',
        ),
    ]
