# Generated by Django 3.2.5 on 2021-10-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_schedule_id_schedule_content_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_content',
            old_name='schedules',
            new_name='schedule_id',
        ),
    ]
