# Generated by Django 3.2.8 on 2021-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('authentication', '0002_usergroup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='schedules',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.Schedule'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='g_id',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.UserGroup'),
        ),
    ]
