# Generated by Django 3.2.5 on 2021-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usergroup_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='g_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='g_id',
            field=models.ManyToManyField(blank=True, to='authentication.UserGroup'),
        ),
    ]
