# Generated by Django 3.2.8 on 2021-10-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('authentication', '0003_auto_20211025_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='schedules',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='g_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='g_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usergroup'),
        ),
    ]
