# Generated by Django 3.2.5 on 2021-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_schedules_schedule_content_schedule_id'),
        ('authentication', '0003_auto_20211022_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='schedules',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='schedule.Schedule'),
        ),
    ]
