# Generated by Django 3.2.8 on 2021-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('authentication', '0004_auto_20211025_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='schedules',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='schedules',
            field=models.ManyToManyField(blank=True, null=True, to='schedule.Schedule'),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='g_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='g_id',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.UserGroup'),
        ),
    ]
