# Generated by Django 3.2.8 on 2021-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211025_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
