# Generated by Django 3.2.8 on 2021-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usergroup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
