# Generated by Django 3.2.8 on 2021-10-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_usergroup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='pin',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
