# Generated by Django 3.2.8 on 2021-10-26 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_usergroup_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='pin',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
