# Generated by Django 3.2.8 on 2021-10-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20211025_2353'),
        ('authentication', '0009_alter_usergroup_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='schedule.Schedule'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='g_id',
            field=models.ManyToManyField(blank=True, to='authentication.UserGroup'),
        ),
    ]
